package hyperliquid

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"testing"
)

// TestTradingActionEncoding checks the wire JSON (and so the signed msgpack)
// of actions. Cases marked python were generated by the official Python SDK
// with _post_action patched to capture the action; the rest follow the
// nktkas schemas.
func TestTradingActionEncoding(t *testing.T) {
	cl := MustParseCloid("0x00000000000000000000000000000001")
	sub := MustParseAddress("0x5e9ee1089755c3435139848e47e6635505d5a13a")
	yes := true
	amt := Decimal("1.5")
	for _, tc := range []struct {
		name string
		a    Action
		want string
	}{
		{"python batchModify", BatchModifyAction{Modifies: []Modify{
			{Oid: OrderRef{Oid: 123}, Order: Order{Asset: 1, IsBuy: true, Price: "1670.1", Size: "0.0147", Type: OrderType{Limit: &LimitOrder{Tif: TifAlo}}}},
			{Oid: OrderRef{Cloid: &cl}, Order: Order{Asset: 0, Price: "60000", Size: "1", ReduceOnly: true, Type: OrderType{Trigger: &TriggerOrder{IsMarket: true, TriggerPx: "59000", Tpsl: TpslStopLoss}}, Cloid: &cl}},
		}}, `{"type":"batchModify","modifies":[{"oid":123,"order":{"a":1,"b":true,"p":"1670.1","s":"0.0147","r":false,"t":{"limit":{"tif":"Alo"}}}},{"oid":"0x00000000000000000000000000000001","order":{"a":0,"b":false,"p":"60000","s":"1","r":true,"t":{"trigger":{"isMarket":true,"triggerPx":"59000","tpsl":"sl"}},"c":"0x00000000000000000000000000000001"}}]}`},
		{
			"python cancelByCloid",
			CancelByCloidAction{Cancels: []CancelByCloid{{Asset: 1, Cloid: cl}}},
			`{"type":"cancelByCloid","cancels":[{"asset":1,"cloid":"0x00000000000000000000000000000001"}]}`,
		},
		{"python scheduleCancel", ScheduleCancelAction{Time: 1700000005000}, `{"type":"scheduleCancel","time":1700000005000}`},
		{"python scheduleCancel unset", ScheduleCancelAction{}, `{"type":"scheduleCancel"}`},
		{
			"python updateLeverage",
			UpdateLeverageAction{Asset: 0, IsCross: false, Leverage: 10},
			`{"type":"updateLeverage","asset":0,"isCross":false,"leverage":10}`,
		},
		{
			"python updateIsolatedMargin",
			UpdateIsolatedMarginAction{Asset: 1, IsBuy: true, Ntli: -1500000},
			`{"type":"updateIsolatedMargin","asset":1,"isBuy":true,"ntli":-1500000}`,
		},
		{"python setReferrer", SetReferrerAction{Code: "ABC"}, `{"type":"setReferrer","code":"ABC"}`},
		{"python createSubAccount", CreateSubAccountAction{Name: "sub1"}, `{"type":"createSubAccount","name":"sub1"}`},
		{
			"python subAccountTransfer",
			SubAccountTransferAction{SubAccountUser: sub, IsDeposit: true, USD: 1000000},
			`{"type":"subAccountTransfer","subAccountUser":"0x5e9ee1089755c3435139848e47e6635505d5a13a","isDeposit":true,"usd":1000000}`,
		},
		{
			"python subAccountSpotTransfer",
			SubAccountSpotTransferAction{SubAccountUser: sub, Token: "PURR:0xc4bf3f870c0e9465323c0b6ed28096c2", Amount: "2.5"},
			`{"type":"subAccountSpotTransfer","subAccountUser":"0x5e9ee1089755c3435139848e47e6635505d5a13a","isDeposit":false,"token":"PURR:0xc4bf3f870c0e9465323c0b6ed28096c2","amount":"2.5"}`,
		},
		{
			"python vaultTransfer",
			VaultTransferAction{VaultAddress: sub, IsDeposit: true, USD: 5000000},
			`{"type":"vaultTransfer","vaultAddress":"0x5e9ee1089755c3435139848e47e6635505d5a13a","isDeposit":true,"usd":5000000}`,
		},
		{"python evmUserModify", EVMUserModifyAction{UsingBigBlocks: true}, `{"type":"evmUserModify","usingBigBlocks":true}`},
		{"python agentSetAbstraction", AgentSetAbstractionAction{Abstraction: AbstractionUnifiedAccount}, `{"type":"agentSetAbstraction","abstraction":"u"}`},
		{"python noop", NoopAction{}, `{"type":"noop"}`},
		{
			"modify always cloid",
			ModifyAction{Oid: OrderRef{Cloid: &cl}, Order: vectorOrder.Orders[0], AlwaysPlace: true},
			`{"type":"modify","oid":"0x00000000000000000000000000000001","order":{"a":4,"b":true,"p":"1670.1","s":"0.0147","r":false,"t":{"limit":{"tif":"Ioc"}}},"a":true}`,
		},
		{"cancel fast", CancelAction{Cancels: []Cancel{{Asset: 1, Oid: 2}}, Fast: true}, `{"type":"cancel","cancels":[{"a":1,"o":2}],"f":true}`},
		{"twapOrder details", TwapOrderAction{
			Twap:    Twap{Asset: 3, IsBuy: true, Size: "10", Minutes: 30, Randomize: true},
			Details: &TwapDetails{Trigger: &TwapActivation{Price: "100", Above: true}},
		}, `{"type":"twapOrder","twap":{"a":3,"b":true,"s":"10","r":false,"m":30,"t":true},"details":{"t":{"p":"100","a":true},"s":null}}`},
		{"twapCancel", TwapCancelAction{Asset: 3, TwapID: 77}, `{"type":"twapCancel","a":3,"t":77}`},
		{"borrowLend full", BorrowLendAction{Operation: BorrowLendRepay, Token: 0}, `{"type":"borrowLend","operation":"repay","token":0,"amount":null}`},
		{
			"vaultModify nulls",
			VaultModifyAction{VaultAddress: sub, AllowDeposits: &yes},
			`{"type":"vaultModify","vaultAddress":"0x5e9ee1089755c3435139848e47e6635505d5a13a","allowDeposits":true,"alwaysCloseOnWithdraw":null}`,
		},
		{
			"createVault nonce",
			CreateVaultAction{Name: "vault", Description: "description", InitialUSD: 100000000},
			`{"type":"createVault","name":"vault","description":"description","initialUsd":100000000,"nonce":1700000000000}`,
		},
		{
			"agentSendAsset",
			AgentSendAssetAction{Destination: sub, DestinationDex: "spot", Token: "USDC:0xeb62eee3685fc4c43992febcd9e75443", Amount: "1"},
			`{"type":"agentSendAsset","destination":"0x5e9ee1089755c3435139848e47e6635505d5a13a","sourceDex":"","destinationDex":"spot","token":"USDC:0xeb62eee3685fc4c43992febcd9e75443","amount":"1","fromSubAccount":"","nonce":1700000000000}`,
		},
		{
			"agentSendAsset from sub",
			AgentSendAssetAction{Destination: sub, Token: "USDC:0xeb62eee3685fc4c43992febcd9e75443", Amount: "1", FromSubAccount: &sub},
			`{"type":"agentSendAsset","destination":"0x5e9ee1089755c3435139848e47e6635505d5a13a","sourceDex":"","destinationDex":"","token":"USDC:0xeb62eee3685fc4c43992febcd9e75443","amount":"1","fromSubAccount":"0x5e9ee1089755c3435139848e47e6635505d5a13a","nonce":1700000000000}`,
		},
		{"userOutcome mergeOutcome max", UserOutcomeAction{MergeOutcome: &MergeOutcome{Outcome: 7}}, `{"type":"userOutcome","mergeOutcome":{"outcome":7,"amount":null}}`},
		{"userOutcome negate", UserOutcomeAction{NegateOutcome: &NegateOutcome{Question: 1, Outcome: 2, Amount: amt}}, `{"type":"userOutcome","negateOutcome":{"question":1,"outcome":2,"amount":"1.5"}}`},
		{"spotUser", SpotUserAction{ToggleSpotDusting: &ToggleSpotDusting{OptOut: true}}, `{"type":"spotUser","toggleSpotDusting":{"optOut":true}}`},
		{"reserveRequestWeight", ReserveRequestWeightAction{Weight: 10}, `{"type":"reserveRequestWeight","weight":10}`},
		{
			"trailingStop pct",
			TrailingStopAction{Asset: 1, IsBuy: false, Size: "0.10", ReduceOnly: true, Retracement: Retracement{Pct: &amt}},
			`{"type":"trailingStop","asset":1,"isBuy":false,"sz":"0.1","reduceOnly":true,"retracement":{"pct":"1.5%"},"activationPx":null}`,
		},
		{
			"trailingStop px",
			TrailingStopAction{Asset: 1, IsBuy: true, Size: "1", Retracement: Retracement{Px: &amt}, ActivationPx: &amt},
			`{"type":"trailingStop","asset":1,"isBuy":true,"sz":"1","reduceOnly":false,"retracement":{"px":"1.5"},"activationPx":"1.5"}`,
		},
	} {
		got, err := encodeAction(tc.a, 1700000000000, Mainnet)
		if err != nil {
			t.Fatalf("%s: %v", tc.name, err)
		}
		if g := compact(t, got); g != tc.want {
			t.Errorf("%s:\n got %s\nwant %s", tc.name, g, tc.want)
		}
	}
}

func TestTradingResponses(t *testing.T) {
	ctx := context.Background()
	_, signer := loadSigningVectors(t)
	newClient := func(resp string) *ExchangeClient {
		c := NewExchangeClient(Testnet, signer)
		c.tr = &recordTransport{resp: resp}
		return c
	}

	id, err := newClient(`{"status":"ok","response":{"type":"twapOrder","data":{"status":{"running":{"twapId":42}}}}}`).
		TwapOrder(ctx, TwapOrderAction{})
	if err != nil || id != 42 {
		t.Errorf("TwapOrder running = %d, %v", id, err)
	}
	var se *StatusError
	_, err = newClient(`{"status":"ok","response":{"type":"twapOrder","data":{"status":{"error":"bad"}}}}`).
		TwapOrder(ctx, TwapOrderAction{})
	if !errors.As(err, &se) || se.Message != "bad" {
		t.Errorf("TwapOrder error = %v", err)
	}
	if err := newClient(`{"status":"ok","response":{"type":"twapCancel","data":{"status":"success"}}}`).
		TwapCancel(ctx, TwapCancelAction{}); err != nil {
		t.Errorf("TwapCancel success = %v", err)
	}
	if err := newClient(`{"status":"ok","response":{"type":"twapCancel","data":{"status":{"error":"gone"}}}}`).
		TwapCancel(ctx, TwapCancelAction{}); fmt.Sprintf("%T", err) != "*hyperliquid.StatusError" || !errors.As(err, &se) || se.Message != "gone" {
		t.Errorf("TwapCancel error = %v", err)
	}
	ms := func(resp string) error {
		_, err := newClient(resp).MultiSig(ctx, Address{}, CancelAction{}, 1, nil)
		return err
	}
	if err := ms(`{"status":"ok","response":{"type":"default","data":{"statuses":["success",{"error":"never placed"}]}}}`); !errors.As(err, &se) || se.Index != 1 {
		t.Errorf("MultiSig batch error = %v", err)
	}
	if err := ms(`{"status":"ok","response":{"type":"default","data":"0x5e9ee1089755c3435139848e47e6635505d5a13a"}}`); err != nil {
		t.Errorf("MultiSig string data = %v", err)
	}
	px := Decimal("1")
	for _, r := range []Retracement{{}, {Pct: &px, Px: &px}} {
		if _, err := json.Marshal(r); err == nil {
			t.Errorf("Marshal(%+v): want error", r)
		}
	}
	addr, err := newClient(`{"status":"ok","response":{"type":"createSubAccount","data":"0x5e9ee1089755c3435139848e47e6635505d5a13a"}}`).
		CreateSubAccount(ctx, CreateSubAccountAction{Name: "x"})
	if err != nil || addr != MustParseAddress("0x5e9ee1089755c3435139848e47e6635505d5a13a") {
		t.Errorf("CreateSubAccount = %v, %v", addr, err)
	}
}
