package hyperliquid

import (
	"context"
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"
)

// signingVectors mirrors testdata/signing_vectors.json, generated by
// testdata/gen_signing_vectors.py with the official Python SDK.
type signingVectors struct {
	PrivateKey string
	Address    Address
	L1         []struct {
		Name         string
		Action       json.RawMessage
		Nonce        uint64
		Vault        *Address
		ExpiresAfter *uint64
		Mainnet      bool
		ConnectionID string
		Signature    json.RawMessage
	}
	UserSigned []struct {
		Name        string
		PrimaryType string
		Types       []typedField
		Action      json.RawMessage
		Mainnet     bool
		Signature   json.RawMessage
	}
	MultiSig []struct {
		Name           string
		MultiSigUser   Address
		OuterSigner    Address
		Nonce          uint64
		Mainnet        bool
		InnerSignature json.RawMessage
		Action         json.RawMessage
		Signature      json.RawMessage
	}
}

func loadSigningVectors(t *testing.T) (signingVectors, *PrivateKeySigner) {
	t.Helper()
	b, err := os.ReadFile("testdata/signing_vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var v signingVectors
	if err := json.Unmarshal(b, &v); err != nil {
		t.Fatal(err)
	}
	signer, err := NewPrivateKeySigner(v.PrivateKey)
	if err != nil {
		t.Fatal(err)
	}
	if signer.Address() != v.Address {
		t.Fatalf("signer address %s, want %s", signer.Address(), v.Address)
	}
	return v, signer
}

func compactJSON(t *testing.T, b []byte) []byte {
	t.Helper()
	var v any
	if err := json.Unmarshal(b, &v); err != nil {
		t.Fatal(err)
	}
	out, err := json.Marshal(v)
	if err != nil {
		t.Fatal(err)
	}
	return out
}

func assertSignature(t *testing.T, name string, sig Signature, want json.RawMessage) {
	t.Helper()
	got, err := json.Marshal(sig)
	if err != nil {
		t.Fatal(err)
	}
	if string(compactJSON(t, got)) != string(compactJSON(t, want)) {
		t.Errorf("%s: signature\n got %s\nwant %s", name, got, want)
	}
}

func TestL1SigningMatchesPython(t *testing.T) {
	v, signer := loadSigningVectors(t)
	for _, tc := range v.L1 {
		h, err := l1ActionHash(tc.Action, tc.Nonce, tc.Vault, tc.ExpiresAfter)
		if err != nil {
			t.Fatalf("%s: %v", tc.Name, err)
		}
		if got := "0x" + hex.EncodeToString(h[:]); got != tc.ConnectionID {
			t.Errorf("%s: connectionId %s, want %s", tc.Name, got, tc.ConnectionID)
		}
		d, err := l1Digest(h, tc.Mainnet)
		if err != nil {
			t.Fatal(err)
		}
		sig, _ := signer.SignHash(context.Background(), d)
		assertSignature(t, tc.Name, sig, tc.Signature)
	}
}

// TestUserSignedActionsMatchPython checks every user-signed action type
// against the Python SDK (or, for actions it lacks, nktkas/hyperliquid's
// EIP-712 types signed by eth_account): EIP-712 type, wire JSON and
// signature.
func TestUserSignedActionsMatchPython(t *testing.T) {
	v, signer := loadSigningVectors(t)
	dest, vault := vectorDest, vectorVault
	usdc := "USDC:0x6d1e7cde53ba9467b783cb7c530ce054"
	evm := SendToEVMWithDataAction{
		Token: "USDC", Amount: "1.0", DestinationRecipient: dest.String(), AddressEncoding: AddressEncodingHex,
		DestinationChainID: 42161, GasLimit: 200000, Data: []byte{0xde, 0xad, 0xbe, 0xef},
	}
	evmEmpty := evm
	evmEmpty.Data = nil
	actions := map[string]userSignedAction{
		"usdSend":                     USDSendAction{Destination: dest, Amount: "1.50"},
		"spotSend":                    SpotSendAction{Destination: dest, Token: "PURR:0xc4bf3f870c0e9465323c0b6ed28096c2", Amount: "0.5"},
		"withdraw3":                   WithdrawAction{Destination: dest, Amount: "10"},
		"usdClassTransfer":            USDClassTransferAction{Amount: "2.0"},
		"usdClassTransfer subaccount": USDClassTransferAction{Amount: "2", ToPerp: true, SubAccount: &vault},
		"sendAsset":                   SendAssetAction{Destination: dest, DestinationDex: "spot", Token: usdc, Amount: "3.25"},
		"sendAsset subaccount": SendAssetAction{
			Destination: dest, SourceDex: "spot", DestinationDex: "xyz", Token: usdc, Amount: "3.25", FromSubAccount: &vault,
		},
		"tokenDelegate":        TokenDelegateAction{Validator: dest, Wei: 123000000},
		"approveAgent":         ApproveAgentAction{AgentAddress: dest, AgentName: "bot"},
		"approveAgent unnamed": ApproveAgentAction{AgentAddress: dest},
		"approveBuilderFee":    ApproveBuilderFeeAction{MaxFeeRate: "0.001", Builder: dest},
		"convertToMultiSigUser": ConvertToMultiSigUserAction{Signers: &MultiSigSigners{
			AuthorizedUsers: []Address{dest, vault}, Threshold: 2, // sorted on the wire
		}},
		"convertToMultiSigUser null":    ConvertToMultiSigUserAction{},
		"userSetAbstraction":            UserSetAbstractionAction{User: dest, Abstraction: AbstractionUnifiedAccount},
		"cDeposit":                      CDepositAction{Wei: 100000000},
		"cWithdraw":                     CWithdrawAction{Wei: 100000000},
		"linkStakingUser":               LinkStakingUserAction{User: dest, IsFinalize: true},
		"stakingLinkDisableTradingUser": StakingLinkDisableTradingUserAction{TradingUser: dest},
		"userPortfolioMargin":           UserPortfolioMarginAction{User: dest},
		"sendToEvmWithData":             evm,
		"sendToEvmWithData empty data":  evmEmpty,
	}
	seen := map[string]bool{}
	for _, tc := range v.UserSigned {
		a, ok := actions[tc.Name]
		if !ok {
			t.Errorf("%s: no Go action for vector", tc.Name)
			continue
		}
		seen[tc.Name] = true
		spec := a.userSignedSpec()
		if got, _ := json.Marshal(spec.types(false)); spec.PrimaryType != tc.PrimaryType || string(got) != string(mustJSON(t, tc.Types)) {
			t.Errorf("%s: EIP-712 type %s %s, want %s %s", tc.Name, spec.PrimaryType, got, tc.PrimaryType, mustJSON(t, tc.Types))
		}
		network := Testnet
		if tc.Mainnet {
			network = Mainnet
		}
		wire, err := encodeAction(a, 1700000000000, network)
		if err != nil {
			t.Fatalf("%s: %v", tc.Name, err)
		}
		if g, w := compact(t, wire), compact(t, tc.Action); g != w {
			t.Errorf("%s: wire\n got %s\nwant %s", tc.Name, g, w)
		}
		sig, err := NewExchangeClient(network, signer).sign(context.Background(), a, wire, 1700000000000)
		if err != nil {
			t.Fatalf("%s: %v", tc.Name, err)
		}
		assertSignature(t, tc.Name, sig, tc.Signature)
	}
	for name := range actions {
		if !seen[name] {
			t.Errorf("%s: no vector", name)
		}
	}
}

func mustJSON(t *testing.T, v any) []byte {
	t.Helper()
	b, err := json.Marshal(v)
	if err != nil {
		t.Fatal(err)
	}
	return b
}

// TestL1HashMatchesNktkas cross-checks expiresAfter handling against the
// independent TypeScript implementation (nktkas/hyperliquid tests/signing).
func TestL1HashMatchesNktkas(t *testing.T) {
	action := []byte(`{"type":"order","orders":[{"a":0,"b":true,"p":"30000","s":"0.1","r":false,"t":{"limit":{"tif":"Gtc"}}}],"grouping":"na"}`)
	vault := MustParseAddress("0x1234567890123456789012345678901234567890")
	exp := uint64(1234567890)
	for _, tc := range []struct {
		vault *Address
		exp   *uint64
		want  string
	}{
		{nil, nil, "25367e0dba84351148288c2233cd6130ed6cec5967ded0c0b7334f36f957cc90"},
		{&vault, nil, "214e2ea3270981b6fd18174216691e69f56872663139d396b10ded319cb4bb1e"},
		{nil, &exp, "c30b002ba3775e4c31c43c1dfd3291dfc85c6ae06c6b9f393991de86cad5fac7"},
		{&vault, &exp, "2d62412aa0fc57441b5189841d81554a6a9680bf07204e1454983a9ca44f0744"},
	} {
		h, err := l1ActionHash(action, 1234567890, tc.vault, tc.exp)
		if err != nil {
			t.Fatal(err)
		}
		if got := hex.EncodeToString(h[:]); got != tc.want {
			t.Errorf("vault=%v exp=%v: got %s, want %s", tc.vault != nil, tc.exp != nil, got, tc.want)
		}
	}
}

func TestSignatureJSONRoundTrip(t *testing.T) {
	in := `{"r":"0xabc","s":"0x1","v":28}`
	var s Signature
	if err := json.Unmarshal([]byte(in), &s); err != nil {
		t.Fatal(err)
	}
	if s.R[31] != 0xbc || s.R[30] != 0x0a || s.S[31] != 1 || s.V != 28 {
		t.Fatalf("decoded %+v", s)
	}
	out, _ := json.Marshal(s)
	if string(out) != in {
		t.Errorf("round trip: %s", out)
	}
}
