package hyperliquid

import (
	"context"
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"
)

// signingVectors mirrors testdata/signing_vectors.json, generated by
// testdata/gen_signing_vectors.py with the official Python SDK.
type signingVectors struct {
	PrivateKey string
	Address    Address
	L1         []struct {
		Name         string
		Action       json.RawMessage
		Nonce        uint64
		Vault        *Address
		ExpiresAfter *uint64
		Mainnet      bool
		ConnectionID string
		Signature    json.RawMessage
	}
	UserSigned []struct {
		Name        string
		PrimaryType string
		Types       []typedField
		Action      json.RawMessage
		Mainnet     bool
		Signature   json.RawMessage
	}
	MultiSig []struct {
		Name           string
		MultiSigUser   Address
		OuterSigner    Address
		Nonce          uint64
		Mainnet        bool
		InnerSignature json.RawMessage
		Action         json.RawMessage
		Signature      json.RawMessage
	}
}

func loadSigningVectors(t *testing.T) (signingVectors, *PrivateKeySigner) {
	t.Helper()
	b, err := os.ReadFile("testdata/signing_vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var v signingVectors
	if err := json.Unmarshal(b, &v); err != nil {
		t.Fatal(err)
	}
	signer, err := NewPrivateKeySigner(v.PrivateKey)
	if err != nil {
		t.Fatal(err)
	}
	if signer.Address() != v.Address {
		t.Fatalf("signer address %s, want %s", signer.Address(), v.Address)
	}
	return v, signer
}

func compactJSON(t *testing.T, b []byte) []byte {
	t.Helper()
	var v any
	if err := json.Unmarshal(b, &v); err != nil {
		t.Fatal(err)
	}
	out, err := json.Marshal(v)
	if err != nil {
		t.Fatal(err)
	}
	return out
}

func assertSignature(t *testing.T, name string, sig Signature, want json.RawMessage) {
	t.Helper()
	got, err := json.Marshal(sig)
	if err != nil {
		t.Fatal(err)
	}
	if string(compactJSON(t, got)) != string(compactJSON(t, want)) {
		t.Errorf("%s: signature\n got %s\nwant %s", name, got, want)
	}
}

func TestL1SigningMatchesPython(t *testing.T) {
	v, signer := loadSigningVectors(t)
	for _, tc := range v.L1 {
		h, err := l1ActionHash(tc.Action, tc.Nonce, tc.Vault, tc.ExpiresAfter)
		if err != nil {
			t.Fatalf("%s: %v", tc.Name, err)
		}
		if got := "0x" + hex.EncodeToString(h[:]); got != tc.ConnectionID {
			t.Errorf("%s: connectionId %s, want %s", tc.Name, got, tc.ConnectionID)
		}
		d, err := l1Digest(h, tc.Mainnet)
		if err != nil {
			t.Fatal(err)
		}
		sig, _ := signer.SignHash(context.Background(), d)
		assertSignature(t, tc.Name, sig, tc.Signature)
	}
}

func TestUserSignedSigningMatchesPython(t *testing.T) {
	v, signer := loadSigningVectors(t)
	for _, tc := range v.UserSigned {
		types := tc.Types
		spec := &userSignedSpec{PrimaryType: tc.PrimaryType, Fields: types[1 : len(types)-1], NonceField: types[len(types)-1].Name}
		d, err := userSignedDigest(spec, tc.Action, false, nil)
		if err != nil {
			t.Fatalf("%s: %v", tc.Name, err)
		}
		sig, _ := signer.SignHash(context.Background(), d)
		assertSignature(t, tc.Name, sig, tc.Signature)
	}
}

// TestL1HashMatchesNktkas cross-checks expiresAfter handling against the
// independent TypeScript implementation (nktkas/hyperliquid tests/signing).
func TestL1HashMatchesNktkas(t *testing.T) {
	action := []byte(`{"type":"order","orders":[{"a":0,"b":true,"p":"30000","s":"0.1","r":false,"t":{"limit":{"tif":"Gtc"}}}],"grouping":"na"}`)
	vault := MustParseAddress("0x1234567890123456789012345678901234567890")
	exp := uint64(1234567890)
	for _, tc := range []struct {
		vault *Address
		exp   *uint64
		want  string
	}{
		{nil, nil, "25367e0dba84351148288c2233cd6130ed6cec5967ded0c0b7334f36f957cc90"},
		{&vault, nil, "214e2ea3270981b6fd18174216691e69f56872663139d396b10ded319cb4bb1e"},
		{nil, &exp, "c30b002ba3775e4c31c43c1dfd3291dfc85c6ae06c6b9f393991de86cad5fac7"},
		{&vault, &exp, "2d62412aa0fc57441b5189841d81554a6a9680bf07204e1454983a9ca44f0744"},
	} {
		h, err := l1ActionHash(action, 1234567890, tc.vault, tc.exp)
		if err != nil {
			t.Fatal(err)
		}
		if got := hex.EncodeToString(h[:]); got != tc.want {
			t.Errorf("vault=%v exp=%v: got %s, want %s", tc.vault != nil, tc.exp != nil, got, tc.want)
		}
	}
}

func TestSignatureJSONRoundTrip(t *testing.T) {
	in := `{"r":"0xabc","s":"0x1","v":28}`
	var s Signature
	if err := json.Unmarshal([]byte(in), &s); err != nil {
		t.Fatal(err)
	}
	if s.R[31] != 0xbc || s.R[30] != 0x0a || s.S[31] != 1 || s.V != 28 {
		t.Fatalf("decoded %+v", s)
	}
	out, _ := json.Marshal(s)
	if string(out) != in {
		t.Errorf("round trip: %s", out)
	}
}
